###### PUT
test_that("PutObject", {
  r <- PutBucket('ross-test')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test', encryption = 'AES256')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test', acl = 'public-read')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test', .md5 = F)
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test', .meta = list(location='beijing', owner='igenecode.com'))
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test', .overwrite = F)
  expect_equal(r$status_code, 200)
})

test_that("CopyObject", {
  r <- PutBucket('ross-test')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test', .meta = list(location='beijing'))
  expect_equal(r$status_code, 200)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt')
  expect_equal(r$status_code, 200)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', encryption = 'AES256')
  expect_equal(r$status_code, 200)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', acl = 'public-read')
  expect_equal(r$status_code, 200)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', meta.directive = 'REPLACE', .meta = list(owner='igenecode.com'))
  expect_equal(r$status_code, 200)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', ETag = 'AAAA', ETag.match = F)
  expect_equal(r$status_code, 200)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', ETag = 'AAAA', ETag.match = T)
  expect_equal(r$status_code, 412)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', since = Sys.time(), modified.since = T)
  expect_equal(r$status_code, 304)
  r <- CopyObject('/ross-test/test2.txt', 'ross-test', 'test2.txt', since = Sys.time(), modified.since = F)
  expect_equal(r$status_code, 200)
})

test_that("PutObjectACL", {
  r <- PutBucket('ross-test')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', 'test')
  expect_equal(r$status_code, 200)
  r <- PutObject('ross-test', 'test.txt', acl = 'public-read')
  expect_equal(r$status_code, 200)
})
